
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ~/data/redis:/data
    networks:
      - backend
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1q2w3e4r
      MYSQL_DATABASE: mall
    ports:
      - "3306:3306"
    volumes:
      - ~/data/mysql:/var/lib/mysql
    networks:
      - backend

networks:
  backend:
    driver: bridge