server:
    port: 8080
spring:
    application:
        name: hfai
    data:
        redis:
            database: 15
            host: 192.168.1.101
            port: 6379
            password:
            jedis:
                pool:
                    max-active: 16
                    max-wait: -1
                    min-idle: 5
                    max-idle: 8
    datasource:
        url: jdbc:mysql://192.168.1.101:3306/mall
        username: root
        password: 1q2w3e4r
        driver-class-name: com.mysql.cj.jdbc.Driver
        # hikari连接池配置
        hikari:
            #连接池名
            pool-name: HikariCP
            #最小空闲连接数
            minimum-idle: 5
            # 空闲连接存活最大时间，默认10分钟
            idle-timeout: 600000
            # 连接池最大连接数，默认是10
            maximum-pool-size: 10
            # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
            auto-commit: true
            # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
            max-lifetime: 1800000
            # 数据库连接超时时间,默认30秒
            connection-timeout: 30000
            # 连接测试query
            connection-test-query: SELECT 1

#mybatisplus的配置
mybatis-plus:
    configuration:
        cache-enabled: true
        use-generated-keys: true
        default-executor-type: REUSE
        use-actual-param-name: true
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 输出SQL log 方便 debug
user:
    expireTimeInSeconds: 360
cache:
    key: user_key

langchain4j:
    open-ai:
        chat-model:
            ## 这个key是启动用的，不是真实key，需要的话请自行购买
            api-key: sk-36f3d7d7-a7b7-4f1d-b5e9-d5f1d5f1d5f1test
            log-requests: true
            log-responses: true
            model-name: gpt-4o-mini
        streaming-chat-model:
            api-key: sk-36f3d7d7-a7b7-4f1d-b5e9-d5f1d5f1d5f1test
            model-name: gpt-4o-mini
logging:
    level:
        dev:
            ai4j:
                openai4j: DEBUG
            changing4j: DEBUG
