server:
    port: 8080
spring:
    application:
        name: hfai
    data:
        redis:
            database: 15
            host: 127.0.0.1
            port: 6379
            password:
            jedis:
                pool:
                    max-active: 16
                    max-wait: -1
                    min-idle: 5
                    max-idle: 8
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/mall
        username: root
        password: 1q2w3e4r
        driver-class-name: com.mysql.cj.jdbc.Driver
        druid:
            max-active: 10
            min-idle: 5
            max-wait: 10000
            initial-size: 5
            validation-query: select 1
            stat-view-servlet:
                enabled: true
                #        login-username: admin
                #        login-password: admin
                #        allow:
                #        deny:
                url-pattern: "/druid/*"
                allow: 47.95.110.151
            web-stat-filter:
                enabled: true
                url-pattern: "/druid/**"
                exclusions: '*.js,*.gif,*.jpg,*.jpeg,*.png,*.css,*.ico,*.jsp,/druid/*'
                principal-session-name: ''
                session-stat-enable: true
                session-stat-max-count: 1000
#mybatisplus的配置
mybatis-plus:
    configuration:
        cache-enabled: true
        use-generated-keys: true
        default-executor-type: REUSE
        use-actual-param-name: true
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 输出SQL log 方便 debug
user:
    expireTimeInSeconds: 360
cache:
    key: user_key

langchain4j:
    open-ai:
        chat-model:
            ## 这个key是启动用的，不是真实key，需要的话请自行购买
            api-key: sk-36f3d7d7-a7b7-4f1d-b5e9-d5f1d5f1d5f1test
            log-requests: true
            log-responses: true
            model-name: gpt-4o-mini
        streaming-chat-model:
            api-key: sk-36f3d7d7-a7b7-4f1d-b5e9-d5f1d5f1d5f1test
            model-name: gpt-4o-mini
logging:
    level:
        dev:
            ai4j:
                openai4j: DEBUG
            changing4j: DEBUG
