apiVersion: v1
kind: Service
metadata:
  name: hfai-dev
  labels:
    app: hfai
    environment: development
spec:
  selector:
    app: hfai
    environment: development
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
