apiVersion: v1
kind: Service
metadata:
  name: hfai-prod
  labels:
    app: hfai
    environment: production
spec:
  selector:
    app: hfai
    environment: production
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
