apiVersion: v1
kind: Service
metadata:
  name: hfai-test
  labels:
    app: hfai
    environment: testing
spec:
  selector:
    app: hfai
    environment: testing
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
